### PR TITLE
Added scrollTo method and export scrollTop, scrollBottom and scrollTo to the context

### PR DESCRIPTION
**Pull request by ingro**
Hello, I've the necessity to scroll the scrollbar to a set position, so I've tought about add a function and also export it and the others to change the scrollbar position to the context, so they are usable like refresh is now.

I could update also the documentation if you need it, let me know!

### CODE REVIEW

**Comment by souhe** [comment]
Thanks for your PR!

I've just improved your solution. In context there is now `scrollTop()`, `scrollBottom()`, `scrollYTo(topPosition)`, `scrollLeft()`, `scrollRight()`, `scrollXTo(leftPosition)`. 

Methods `scrollXTo()` and `scrollYTo()` takes positive value as argument, not negative like in your commit.

What do you think about my changes(ae0463d)?

**Comment by ingro** [comment]
Yep I guess that's a more complete solution, I just forgot about the horizontal scroller... good work! :)

**Comment by souhe** [comment]
So I'll add this changes to next release.

**Comment by souhe** [comment]
Thanks for your contribution :)

**Comment by ingro** [comment]
Great, I really needed that, thanks for your work with this project!

**Pull request merged**
