### PR TITLE
Fixed bug about passive wheele vent listeners in chrome 

### PR DESCRIPTION
**Pull request by apenab**
Solution to the problem #128, more info here => [Document-level-passive-wheel-event-listeners](https://github.com/sahel-sh/Document-level-passive-wheel-event-listeners/blob/master/Explainer.md)

### CODE REVIEW

**Comment by souhe** [comment]
@apenab thank you!

**Comment by joetidee** [comment]
Will a new version be published to npm soon?

**Comment by zhaosuxia** [comment]
Please update the latest version to NPM! thanks.

**Comment by apenab** [comment]
@souhe We need this update in NPM, some problem that can help you ?

**Pull request merged**
