### PR TITLE
Access PropTypes via prop-types package & update react-motion to 0.5.0

### PR DESCRIPTION
**Pull request by sizeight**

### CODE REVIEW

**Comment by el1f** [comment]
Can we have this merged already guys?

**Comment by abderrahmane-tj** [comment]
Is there any reason why this is still not merged ?

**Comment by souhe** [comment]
Hey @abderrahmane-tj :)
I'm the only reason and I'm really sorry for it. 

@sizeight thanks for your work!

I'm merging it!

**Comment by abderrahmane-tj** [comment]
@souhe when I use this as package, I notice that the generated dist still uses `React.PropTypes`

**Comment by souhe** [comment]
hmmm, you're right! I've just published new version 0.5.3 with properly generated dist :)
Please let me know if everything is ok with this version.

Thanks :)

**Comment by abderrahmane-tj** [comment]
@souhe Thanks for the prompt update ! It looks good to me now.

**Pull request merged**
