### PR TITLE
Accessing PropTypes via the main React package is deprecated

### PR DESCRIPTION
**Pull request by mishantrop**
https://github.com/souhe/reactScrollbar/issues/93

### CODE REVIEW

**Comment by mishantrop** [comment]
Hm...
```
$ npm run test

> react-scrollbar@0.5.1 test ***/reactScrollbar
> karma start karma.config.js --single-run --browsers PhantomJS


START:
07 07 2017 21:56:03.461:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
07 07 2017 21:56:03.467:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
07 07 2017 21:56:03.573:INFO [launcher]: Starting browser PhantomJS
07 07 2017 21:56:05.504:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket dwAPRufX95Hy6Sc-AAAA with id 48787256
PhantomJS 2.1.1 (Windows 7 0.0.0) WARN: 'Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.'
ERROR: 'Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning.'
  ScrollArea component
    √ Should render children and both scrollbars
    √ Should render with tabindex set
    √ Could render only vertical scrollbar
    √ Could render only horizontal scrollbar
    √ Should change content element class when contentClassName prop is used
    √ Should have proper element style when contentStyle prop is used
    √ Should have proper scrollbars styles
    √ normalizeTopPosition() should returns proper value
    √ normalizeLeftPosition() should returns proper value
    √ handleWheel method work properly when scrolling down
    √ handleWheel method work properly when scrolling up and actual topPosition is 0
    √ handleWheel method work properly when scrolling down more then content height
    √ handleWheel method work properly when scrolling right
    √ handleWheel method work properly when scrolling left and actual leftPosition is 0
    √ handleWheel method work properly when scrolling right more then content height
    √ handleWheel method should scroll down on scrollRight wheel event when revertWheelAxes prop is set to true
    √ handleWheel method should scroll down on scrollRight wheel event when revertWheelAxes prop is set to true
    √ handleKeyDown method works properly when pressing key down
    √ handleKeyDown method works properly when pressing key right
    √ handleKeyDown method works properly when pressing key page down
    √ handleKeyDown method should not scroll if input element is selected
    √ scrollBottom() method should work when content is smaller then container
    √ scrollBottom() method should scroll to bottom
    √ scrollBottom() should be impossible when there is disabled vertical scroll
    √ scrollRight() method should work when content is smaller then container
    √ scrollRight() method should scroll to right
    √ scrollRight() should be impossible when there is disabled horizontal scroll
    √ scrollLeft() method should scroll to left
    √ scrollTop() method should scroll to top
  ScrollBar component
    √ Vertical should have proper class
    √ Vertical should have proper container styles
    √ Vertical should have proper scrollbar styles
    √ Horizontal should have proper class
    √ Horizontal should have proper container styles
    √ Horizontal should have proper scrollbar styles
    √ ScrollBar should be in proper position
    √ ScrollBar should have proper size
    √ Should propagate onMove event after move vertical scrollbar
    √ Should propagate onMove event after move horizontal scrollbar
    √ Should propagate onMove event multiple times
    √ Should be possible to set min scrollbar size
    √ Method calculateFractionalPosition should work properly for realSize: 300, containerSize: 100, position: 0
    √ Method calculateFractionalPosition should work properly for realSize: 300, containerSize: 100, position: 200
    √ Method calculateFractionalPosition should work properly for realSize: 300, containerSize: 100, position: 200
    √ Method calculateFractionalPosition should work properly for realSize: 160, containerSize: 80, position: 20
    √ Position of scrollbar should be proper when minScrollBarSize is set
    √ vertical scrollbar container click should move scrollbar
    √ vertical scrollbar container click should move scrollbar when minScrollbar size is set
    √ horizontal scrollbar container click should move scrollbar
    √ horizontal scrollbar container click should move scrollbar when minScrollbar size is set
  utils
    positiveOrZero
      √ should return the same value for positive
      √ should return 0 for 0 as argument
      √ should return 0 for for negative argument value
    modifyObjValues
      √ should return object with modified all keys
      √ should return the same object when no second argument
    isReact13
      √ should return true for React 0.13

Finished in 0.021 secs / 0.098 secs @ 21:56:05 GMT+0300 (Московское время (зима))

SUMMARY:
√ 56 tests completed
```

**Comment by souhe** [comment]
@mishantrop hey, thanks for your work but I cannot merge it. The build is failing, there are too many changes (almost everything is changed) for one PR. You even changed example app link and copyrights.

**Comment by mishantrop** [comment]
Of course, my pull request was a little bit smaller a half year ago.
Anyway, thanks for your work too. I just trying to maintain this component for some project, because your one is outdated.

**Comment by souhe** [comment]
Right, it is a little bit outdated. I have a plans update this lib to make it works better :) I'm starting today!

**Pull request closed without merging**
